Page({
    data:{
    listDatas:[{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      },{
        headImg:'../../images/head.png',
        name:'一瞬的永恒',
        desc:'参加微信小程序培训',
        time:'2016-10-01'
      }]
    }
})