Page({
  data: {
    userInfo: {}
  },
  openScrollView:function(){
    wx.navigateTo({
      url:'../component/scrollview/scrollview'
    });
  },
  openSwiper:function(){
    wx.navigateTo({
      url:'../component/swiper/swiper'
    });
  },
  openIcon:function(){
    wx.navigateTo({
      url:'../component/icons/icons'
    });
  },
  openText:function(){
    wx.navigateTo({
      url:'../component/texts/texts'
    });
  },
  openProgress:function(){
    wx.navigateTo({
      url:'../component/progress/progress'
    });
  },
  openForms:function(){
    wx.navigateTo({
      url:'../component/forms/forms'
    });
  },
  openActions:function(){
    wx.navigateTo({
      url:'../component/actions/actions'
    });
  },
  openAudio:function(){
    wx.navigateTo({
      url:'../component/audio/audio'
    });
  },
  openVideo :function(){
    wx.navigateTo({
      url:'../component/video/video'
    });
  },
  openImage :function(){
    wx.navigateTo({
      url:'../component/images/images'
    });
  }
})
